fixes:
  - "/home/circleci/::"

#ignore:
#  - **/*_ViewBinding.class
#  - **/*InjectAdapter.class
#  - **/android/support/**/*.class
#  - **/com/google/**/*.class
#  - **/com/birbit/**/*.class
#  - **/butterknife/**/*.class
#  - **/com/arellomobile/**/*.class
#  - **/net/ganin/darv/**/*.class
#  - **/*ViewStateProvider.class
#  - **/*PresentersBinder.class
#  - **/events/**/*.class
#  - **/model/impl/*.class
#  - **/injection/**/*.class
#  - **/*MemberInject.*
#  - **/*$$Factory*.*
#  - **/*..State*.*
#  - **/*_ViewBinding*.*



